version: 2

sphinx:
  builder: html
  configuration: conf.py

python:
  version: 3.8
  install:
    - requirements: requirements.txt
    - method: pip
      path: .

formats:
  - pdf
  - epub

build:
  os: ubuntu-20.04 t
